#!/bin/sh
valgrind -v --num-callers=40 --track-fds=yes --gen-suppressions=all --suppressions=valgrind.supp --suppressions=/usr/lib/valgrind/debian.supp --suppressions=/usr/lib/valgrind/python2.supp ./realms.exe -v
